Title: doctest.DebugRunner Class Overview
URL: https://docs.python.org/3/library/doctest.html
Summary: The `doctest.DebugRunner` class is a subclass of `DocTestRunner` designed to halt execution and raise exceptions upon failure. It raises an `UnexpectedException` for unexpected errors and a `DocTestFailure` when output does not match expected results, providing detailed context about the test and output.
---

_class_ doctest.DebugRunner(_checker =None_, _verbose =None_, _optionflags =0_)[¶](https://docs.python.org/3/library/doctest.html#doctest.DebugRunner "Link to this definition")
    
A subclass of [`DocTestRunner`](https://docs.python.org/3/library/doctest.html#doctest.DocTestRunner "doctest.DocTestRunner") that raises an exception as soon as a failure is encountered. If an unexpected exception occurs, an [`UnexpectedException`](https://docs.python.org/3/library/doctest.html#doctest.UnexpectedException "doctest.UnexpectedException") exception is raised, containing the test, the example, and the original exception. If the output doesn’t match, then a [`DocTestFailure`](https://docs.python.org/3/library/doctest.html#doctest.DocTestFailure "doctest.DocTestFailure") exception is raised, containing the test, the example, and the actual output.
For information about the constructor parameters and methods, see the documentation for [`DocTestRunner`](https://docs.python.org/3/library/doctest.html#doctest.DocTestRunner "doctest.DocTestRunner") in section [Advanced API](https://docs.python.org/3/library/doctest.html#doctest-advanced-api).
There are two exceptions that may be raised by [`DebugRunner`](https://docs.python.org/3/library/doctest.html#doctest.DebugRunner "doctest.DebugRunner") instances: 

_exception_ doctest.DocTestFailure(_test_ , _example_ , _got_)[¶](https://docs.python.org/3/library/doctest.html#doctest.DocTestFailure "Link to this definition")
    
An exception raised by [`DocTestRunner`](https://docs.python.org/3/library/doctest.html#doctest.DocTestRunner "doctest.DocTestRunner") to signal that a doctest example’s actual output did not match its expected output. The constructor arguments are used to initialize the attributes of the same names.
[`DocTestFailure`](https://docs.python.org/3/library/doctest.html#doctest.DocTestFailure "doctest.DocTestFailure") defines the following attributes: 

DocTestFailure.test[¶](https://docs.python.org/3/library/doctest.html#doctest.DocTestFailure.test "Link to this definition")
    
The [`DocTest`](https://docs.python.org/3/library/doctest.html#doctest.DocTest "doctest.DocTest") object that was being run when the example failed. 

DocTestFailure.example[¶](https://docs.python.org/3/library/doctest.html#doctest.DocTestFailure.example "Link to this definition")
    
The [`Example`](https://docs.python.org/3/library/doctest.html#doctest.Example "doctest.Example") that failed. 

DocTestFailure.got[¶](https://docs.python.org/3/library/doctest.html#doctest.DocTestFailure.got "Link to this definition")
    
The example’s actual output. 

_exception_ doctest.UnexpectedException(_test_ , _example_ , _exc_info_)[¶](https://docs.python.org/3/library/doctest.html#doctest.UnexpectedException "Link to this definition")
    
An exception raised by [`DocTestRunner`](https://docs.python.org/3/library/doctest.html#doctest.DocTestRunner "doctest.DocTestRunner") to signal that a doctest example raised an unexpected exception. The constructor arguments are used to initialize the attributes of the same names.
[`UnexpectedException`](https://docs.python.org/3/library/doctest.html#doctest.UnexpectedException "doctest.UnexpectedException") defines the following attributes: 

UnexpectedException.test[¶](https://docs.python.org/3/library/doctest.html#doctest.UnexpectedException.test "Link to this definition")
    
The [`DocTest`](https://docs.python.org/3/library/doctest.html#doctest.DocTest "doctest.DocTest") object that was being run when the example failed. 

UnexpectedException.example[¶](https://docs.python.org/3/library/doctest.html#doctest.UnexpectedException.example "Link to this definition")
    
The [`Example`](https://docs.python.org/3/library/doctest.html#doctest.Example "doctest.Example") that failed. 

UnexpectedException.exc_info[¶](https://docs.python.org/3/library/doctest.html#doctest.UnexpectedException.exc_info "Link to this definition")
    
A tuple containing information about the unexpected exception, as returned by [`sys.exc_info()`](https://docs.python.org/3/library/sys.html#sys.exc_info "sys.exc_info").
## Soapbox[¶](https://docs.python.org/3/library/doctest.html#soapbox "Link to this heading")
As mentioned in the introduction, [`doctest`](https://docs.python.org/3/library/doctest.html#module-doctest "doctest: Test pieces of code within docstrings.") has grown to have three primary uses:
  1. Checking examples in docstrings.
  2. Regression testing.
  3. Executable documentation / literate testing.