Title: Python 3 Changelog Updates
URL: https://docs.python.org/3/whatsnew/changelog.html
Summary: This update includes the addition of missing TCP socket options from Linux and improvements to memory usage in `urllib.parse.unquote()` and `urllib.parse.unquote_to_bytes()`. It also notes a fix for a `TypeError` raised by `inspect.signature`.
---

Patch by Kumar Aditya.
  * [gh-98030](https://github.com/python/cpython/issues/98030): Add missing TCP socket options from Linux: `TCP_MD5SIG`, `TCP_THIN_LINEAR_TIMEOUTS`, `TCP_THIN_DUPACK`, `TCP_REPAIR`, `TCP_REPAIR_QUEUE`, `TCP_QUEUE_SEQ`, `TCP_REPAIR_OPTIONS`, `TCP_TIMESTAMP`, `TCP_CC_INFO`, `TCP_SAVE_SYN`, `TCP_SAVED_SYN`, `TCP_REPAIR_WINDOW`, `TCP_FASTOPEN_CONNECT`, `TCP_ULP`, `TCP_MD5SIG_EXT`, `TCP_FASTOPEN_KEY`, `TCP_FASTOPEN_NO_COOKIE`, `TCP_ZEROCOPY_RECEIVE`, `TCP_INQ`, `TCP_TX_DELAY`.
  * [gh-88500](https://github.com/python/cpython/issues/88500): Reduced the memory usage of [`urllib.parse.unquote()`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.unquote "urllib.parse.unquote") and [`urllib.parse.unquote_to_bytes()`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.unquote_to_bytes "urllib.parse.unquote_to_bytes") on large values.
  * [gh-96127](https://github.com/python/cpython/issues/96127): `inspect.signature` was raising `TypeError` on call with mock objects. Now it correctly returns `(*args, **kwargs)` as inferred signature.
  * [gh-95882](https://github.com/python/cpython/issues/95882): Fix a 3.11 regression in [`asynccontextmanager()`](https://docs.python.org/3/library/contextlib.html#contextlib.asynccontextmanager "contextlib.asynccontextmanager"), which caused it to propagate exceptions with incorrect tracebacks and fix a 3.11 regression in [`contextmanager()`](https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager "contextlib.contextmanager"), which caused it to propagate exceptions with incorrect tracebacks for [`StopIteration`](https://docs.python.org/3/library/exceptions.html#StopIteration "StopIteration").
  * [gh-78707](https://github.com/python/cpython/issues/78707): Deprecate passing more than one positional argument to [`pathlib.PurePath.relative_to()`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.relative_to "pathlib.PurePath.relative_to") and [`is_relative_to()`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.is_relative_to "pathlib.PurePath.is_relative_to").
  * [gh-92122](https://github.com/python/cpython/issues/92122): Fix reStructuredText syntax errors in docstrings in the [`enum`](https://docs.python.org/3/library/enum.html#module-enum "enum: Implementation of an enumeration class.") module.
  * [gh-91851](https://github.com/python/cpython/issues/91851): Optimize the [`Fraction`](https://docs.python.org/3/library/fractions.html#fractions.Fraction "fractions.Fraction") arithmetics for small components.
  * [bpo-24132](https://bugs.python.org/issue?@action=redirect&bpo=24132): Make [`pathlib.PurePath`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath "pathlib.PurePath") and [`Path`](https://docs.python.org/3/library/pathlib.html#pathlib.Path "pathlib.Path") subclassable (private to start). Previously, attempting to instantiate a subclass resulted in an [`AttributeError`](https://docs.python.org/3/library/exceptions.html#AttributeError "AttributeError") being raised. Patch by Barney Gale.
  * [bpo-40447](https://bugs.python.org/issue?@action=redirect&bpo=40447): Accept [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike "os.PathLike") (such as [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html#pathlib.Path "pathlib.Path")) in the `stripdir` arguments of [`compileall.compile_file()`](https://docs.python.org/3/library/compileall.html#compileall.compile_file "compileall.compile_file") and [`compileall.compile_dir()`](https://docs.python.org/3/library/compileall.html#compileall.compile_dir "compileall.compile_dir").
  * [bpo-36880](https://bugs.python.org/issue?@action=redirect&bpo=36880): Fix a reference counting issue when a [`ctypes`](https://docs.python.org/3/library/ctypes.html#module-ctypes "ctypes: A foreign function library for Python.") callback with return type [`py_object`](https://docs.python.org/3/library/ctypes.html#ctypes.py_object "ctypes.py_object") returns `None`, which could cause crashes.